### ISSUE TITLE
TypeError: Index.name must be a hashable type

### ISSUE THREAD

**Issue by jmche** [sharebook-kr/pykrx#28]
api.py
delete the line: df.columns.name = get_market_ticker_name(ticker)
it will be ok

**Comment by mr-yoo** [comment]
Could you tell me which API you used? It would be better if you could attach code you wrote.

**Comment by jmche** [comment]
Traceback (most recent call last):
  File "python3_getdata.py", line 209, in <module>
    index_data = stock.get_market_ohlcv_by_date("20160118", todayDate, "kosdaq")
  File "python3.8/site-packages/pykrx/stock/api.py", line 91, in get_market_ohlcv_by_date
    df.columns.name = get_market_ticker_name(ticker)
  File "python3.8/site-packages/pandas/core/indexes/base.py", line 1186, in name
    maybe_extract_name(value, None, type(self))
  File "python3.8/site-packages/pandas/core/indexes/base.py", line 5661, in maybe_extract_name
    raise TypeError(f"{cls.__name__}.name must be a hashable type")
TypeError: Index.name must be a hashable type

**Comment by mr-yoo** [comment]
`get_market_ohlcv_by_date` should be used with a ticker rather than `kosdaq`.

```python
df = stock.get_market_ohlcv_by_date("20160118", "20160229", "005930")
df.head()
```

`get_index_ohlcv_by_date` should be used with a ticker consisting of numbers after the latest update. See API description of  [get_index_ohlcv_by_date](https://github.com/sharebook-kr/pykrx#2123-%EC%9D%B8%EB%8D%B1%EC%8A%A4-ohlcv-%EC%A1%B0%ED%9A%8C).
(In previous versions, `코스피` or `코스닥` was available for the ticker.)

You can use `get_index_ohlcv_by_date` function using the defined ticker as follows.
```python
index_data = stock.get_index_ohlcv_by_date("20160118", "20160229", "1001")
index_data.head()
```

See the following link for list of index.
[index list](https://github.com/sharebook-kr/pykrx#2121-%EC%9D%B8%EB%8D%B1%EC%8A%A4-%EC%A2%85%EB%A5%98-%EC%A1%B0%ED%9A%8C)

**Comment by jmche** [comment]
I accepted your suggestion that used the "get_index_ohlcv_by_date" function but I get one problem is that it updates too slow.
So I think that delete the line which I mentioned and run the API is much better than using the "get_index_ohlcv_by_date" function. 
Maybe you could fix it in the next version.

**Comment by mr-yoo** [comment]
The current version requires additional time to get names of all tickers on the first request. However, after the first request, the name are reused, so requests are executed without additional time.

I agree with you that API execution can be slow. In the next version, I will modify PYKRX so that name of ticker is not included by default to speed up. Instead, I will control the output of the name by adding parameters to the function as shown below.

```
df =  stock.get_index_ohlcv_by_date("20160118", "20160229", "1001", name_display=True)
```

**Comment by jmche** [comment]
I guess I didn't say it clearly. 
It's not only execution take more time but also the update time point is much slower. 

The "get_market_ohlcv_by_date" function update the data on 16:00, but the "get_index_ohlcv_by_date" is much slower than that(more than 1 or 2 hours I guess).

In my case, The update time point is much more important that's why I have to use the "get_market_ohlcv_by_date" function.

**Comment by mr-yoo** [comment]
The latest edition (0.1.42) has been released. 
- A parameter `name_display` determines whether name of stocks is output. 
- The name is not displayed by default.

> The current version requires additional time to get names of all tickers on the first request. However, after the first request, the name are reused, so requests are executed without additional time.
> 
> I agree with you that API execution can be slow. In the next version, I will modify PYKRX so that name of ticker is not included by default to speed up. Instead, I will control the output of the name by adding parameters to the function as shown below.
> 
> ```
> df =  stock.get_index_ohlcv_by_date("20160118", "20160229", "1001", name_display=True)
> ```

----
Function `get_market_xx` inquires individual stock price, and Function `get_index_xx` inquires index information. When data is updated depends on the web server.
